### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by fxzjshm** [eNTeR-Studio/BlackAndWhiteForest#7]
- [ ] Test .ogg file on OS X.  
- [ ] Add [szszss/AsmEventBus](https://github.com/szszss/AsmEventBus), instead of BAWFEventBus. 
- [ ] Add [MIT](https://github.com/szszss/AsmEventBus/blob/develop/LICENSE) and [Apache License](https://github.com/libgdx/libgdx/blob/master/LICENSE) and let users accept. 

~~\- [ ] Replace all the pictures into .svg files.~~
- [ ] Add Gdx-dialogs and html support. 
- [ ] Use cookie to save properties in html. 
- [ ] Remove useless huge files in history.
